#ifndef _LIBINFRA_NAMESPACE_H
#define _LIBINFRA_NAMESPACE_H

enum InfraNamespace {
  INFRA_NAMESPACE_NULL = 0,
  INFRA_NAMESPACE_HTML,
  INFRA_NAMESPACE_SVG,
  INFRA_NAMESPACE_XLINK,
  INFRA_NAMESPACE_XML,
  INFRA_NAMESPACE_XMLNS,

  NUM_INFRA_NAMESPACE
};

#endif /* _LIBINFRA_NAMESPACE_H */
